#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running CSharpier formatting..."

# Add || true to prevent grep from exiting with error code 1 if no files match
STAGED_CS_FILES=$(git diff --cached --name-only --diff-filter=d | grep '\.cs$' || true)

if [ -n "$STAGED_CS_FILES" ]; then
  # Use --check to see if it's a syntax error, or just run it to format
  dotnet csharpier $STAGED_CS_FILES || exit 1

  echo "$STAGED_CS_FILES" | xargs git add
  echo "Formatting complete."
else
  echo "No C# files staged."
fi
